BEGIN;

-- CREATE TABLE IF NOT EXISTS users (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   email TEXT UNIQUE,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS sessions (
--   id TEXT PRIMARY KEY,
--   user_id INTEGER REFERENCES users(id),
--   expires_at DATETIME NOT NULL,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

CREATE TABLE IF NOT EXISTS feeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL UNIQUE,
  -- user_id INTEGER REFERENCES users(id),
  title TEXT NOT NULL,
  updated TEXT NOT NULL,
  etag TEXT,
  raw TEXT,
  created TEXT DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL,
  feed INTEGER REFERENCES feeds(id),
  title TEXT NOT NULL,
  description TEXT,
  pubDate TEXT NOT NULL,
  read INTEGER CHECK (read IN (0, 1)) DEFAULT 0,
  star INTEGER CHECK (read IN (0, 1)) DEFAULT 0,
  created TEXT DEFAULT CURRENT_TIMESTAMP
) STRICT;

COMMIT;

PRAGMA foreign_keys = ON;